### PR TITLE
Fixes and refactoring of notificationsFCM

### LINKED ISSUE #6120: 2024.6 crashes when gcm enabled and notification is sent
Hi, 

i upgraded on my system to 2024.6. I noticed it had crashed several times. 

after analysis i found it always happens at the moment a notification is sent, then i get logging like this:

```
2024-07-12 07:55:08.843  dzVents: Handling events for: "Volvo", value: "Locked"
2024-07-12 07:55:08.843  dzVents: volvo: ------ Start internal script: Volvo: Device: "Volvo (Volvo)", Index: 1258
2024-07-12 07:55:08.843  dzVents: Debug: volvo: Device Volvo was changed to 1,Locked
2024-07-12 07:55:08.843  dzVents: Debug: volvo: Device was locked
2024-07-12 07:55:08.844  dzVents: Debug: volvo: Processing device-adapter for Volvo-SunRoof: Switch device adapter
2024-07-12 07:55:08.844  dzVents: Debug: volvo: sunroof is open
2024-07-12 07:55:08.844  dzVents: !Info: volvo: Notification sent: Auto afgesloten met open dak
2024-07-12 07:55:08.845  dzVents: volvo: ------ Finished Volvo
2024-07-12 07:55:08.845  Status: EventSystem: Script event triggered: /home/domoticz/domoticz/dzVents/runtime/dzVents.lua
2024-07-12 07:55:08.874  Status: Notification: Volvo
2024-07-12 07:55:08.875  Notification sent (browser) => Success
2024-07-12 07:55:09.039  Error: Domoticz(pid:1543267, tid:1545832('SendMessageEx')) received fatal signal 11 (Segmentation fault)
2024-07-12 07:55:09.039  Error: siginfo address=0x3e900178c63, address=0x7fb9da09fc
2024-07-12 07:55:09.624  Error: Failed to start gdb, will use backtrace() for printing stack frame
2024-07-12 07:55:09.629  Error: #0  /home/domoticz/domoticz/domoticz :  + 0x32c3dc [0x555dabc3dc]
2024-07-12 07:55:09.629  Error: #1  /home/domoticz/domoticz/domoticz : signal_handler(int, siginfo_t*, void*) + 0x250 [0x555dabce70]
2024-07-12 07:55:09.629  Error: #2  linux-vdso.so.1 : __kernel_rt_sigreturn + 0 [0x7fba6657b0]
2024-07-12 07:55:09.629  Error: #3  /lib/aarch64-linux-gnu/libc.so.6 :  + 0x80a10 [0x7fb9da0a10]
2024-07-12 07:55:09.629  Error: #4  /lib/aarch64-linux-gnu/libc.so.6 : gsignal + 0x1c [0x7fb9d5a76c]
2024-07-12 07:55:09.629  Error: #5  linux-vdso.so.1 : __kernel_rt_sigreturn + 0 [0x7fba6657b0]
2024-07-12 07:55:09.629  Error: #6  /lib/aarch64-linux-gnu/libc.so.6 :  + 0x9a300 [0x7fb9dba300]
2024-07-12 07:55:09.629  Error: #7  /home/domoticz/domoticz/domoticz : std::basic_streambuf<char, std::char_traits<char> >::xsputn(char const*, long) + 0x64 [0x555e1097f4]
2024-07-12 07:55:09.629  Error: #8  /home/domoticz/domoticz/domoticz : std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) + 0x154 [0x555e116acc]
2024-07-12 07:55:09.629  Error: #9  /home/domoticz/domoticz/domoticz : CNotificationFCM::SendMessageImplementation(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) + 0xa24 [0x555df0a644]
2024-07-12 07:55:09.629  Error: #10 /home/domoticz/domoticz/domoticz : CNotificationBase::SendMessageEx(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) + 0x174 [0x555df011a4]
2024-07-12 07:55:09.629  Error: #11 /home/domoticz/domoticz/domoticz :  + 0x77e39c [0x555df0e39c]
2024-07-12 07:55:09.629  Error: #12 /home/domoticz/domoticz/domoticz :  + 0x83fa84 [0x555dfcfa84]
2024-07-12 07:55:09.629  Error: #13 /lib/aarch64-linux-gnu/libc.so.6 :  + 0x7ee58 [0x7fb9d9ee58]
2024-07-12 07:55:09.629  Error: #14 /lib/aarch64-linux-gnu/libc.so.6 :  + 0xe7f9c [0x7fb9e07f9c]

```

The code of the dzvents in this example is 
```
return {
	on = {
		devices = {
			'Volvo',  -- Lock Device of the volvo,
			'test'  -- for testing purposes
 		}
	},
	logging = {
		level = domoticz.LOG_DEBUG, -- adjust to the whatever loglevel you like
		marker = 'volvo',
	},
	data = {
	    lastLockedState = { initial = false }
	},
	execute = function(domoticz, device)
		domoticz.log('Device ' .. device.name .. ' was changed to ' ..device.nValue..','..device.sValue, domoticz.LOG_DEBUG)
		-- check if device was locked
		if (device.active) then
		    domoticz.log('Device was locked',domoticz.LOG_DEBUG)
		    -- check if sunroof is open
		    local SR=domoticz.devices("Volvo-SunRoof") -- Name of your sunroof device
		    if SR.active then
		        domoticz.log("sunroof is open",domoticz.LOG_DEBUG)
		        notificationMessage = "Auto afgesloten met open dak" 
		        domoticz.notify("Volvo",notificationMessage,domoticz.PRIORITY_HIGH)
		        domoticz.log("Notification sent: "..notificationMessage,domoticz.LOG_FORCE)
		    else
		        domoticz.log("sunroof is closed",domoticz.LOG_DEBUG)
		    end
		else
		    domoticz.log('Device was unlocked',domoticz.LOG_DEBUG)
		end
	end
}
```

The crash happens at the domoticz.notify statement, cause the Notification Sent is never in the log.

I have several scripts like this and they now all crashed at the moment of the domoticz.notify statement (and all worked fine before 2024.6)

In the 2024.6 release log i noticed a change to GCM cloud messaging, so i disabled Google Cloud Messaging in the settings, and found out all my scripts are running fine again. Enabling GCM cause domoticz to crash again when sending notifications. so the issue is related to the cloud messaging code

### LINKED ISSUE #6126: Warnings during compilation gcc12.3
There are some warning during compilation gcc12.3 

```
In file included from /home/user/openwrt_2305/build_dir/target-mipsel_24kc_musl/domoticz-db721738a19595d92f30eda8f56d0d4d250fd78a/main/clx_unzip.h:53,
                 from /home/user/openwrt_2305/build_dir/target-mipsel_24kc_musl/domoticz-db721738a19595d92f30eda8f56d0d4d250fd78a/main/SQLHelper.cpp:26:
/home/user/openwrt_2305/build_dir/target-mipsel_24kc_musl/domoticz-db721738a19595d92f30eda8f56d0d4d250fd78a/main/unzip_iterator.h:53:50: warning: 'template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator' is deprecated [-Wdeprecated-declarations]
   53 |         class basic_unzip_iterator : public std::iterator<std::input_iterator_tag, basic_unzip_stream<CharT, Traits> > {
      |                                                  ^~~~~~~~
In file included from /home/user/openwrt_2305/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/mipsel-openwrt-linux-musl/include/c++/12.3.0/string:45,
                 from /home/user/openwrt_2305/build_dir/target-mipsel_24kc_musl/domoticz-db721738a19595d92f30eda8f56d0d4d250fd78a/main/stdafx.h:18,
                 from /home/user/openwrt_2305/build_dir/target-mipsel_24kc_musl/domoticz-db721738a19595d92f30eda8f56d0d4d250fd78a/CMakeFiles/domoticz.dir/cmake_pch.hxx:5,
                 from <command-line>:
/home/user/openwrt_2305/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/mipsel-openwrt-linux-musl/include/c++/12.3.0/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~





[97/273] Building CXX object CMakeFiles/domoticz.dir/hardware/EnOceanESP3.cpp.o
/home/user/openwrt_2305/build_dir/target-mipsel_24kc_musl/domoticz-db721738a19595d92f30eda8f56d0d4d250fd78a/hardware/EnOceanESP3.cpp: In member function 'void CEnOceanESP3::ParseERP1Packet(uint8_t*, uint16_t, uint8_t*, uint8_t)':
/home/user/openwrt_2305/build_dir/target-mipsel_24kc_musl/domoticz-db721738a19595d92f30eda8f56d0d4d250fd78a/hardware/EnOceanESP3.cpp:3343:112: warning: format '%ld' expects argument of type 'long int', but argument 5 has type 'time_t' {aka 'long long int'} [-Wformat=]
 3343 |                                                 Log(LOG_NORM, "RPS teach-in requires %u actions in less than %ldms to complete", TEACH_NB_REQUESTS, TEACH_MAX_DELAY);
      |                                                                                                              ~~^
      |                                                                                                                |
      |                                                                                                                long int
      |                                                                                                              %lld




[148/273] Building CXX object CMakeFiles/domoticz.dir/hardware/OpenWebNetTCP.cpp.o
/home/user/openwrt_2305/build_dir/target-mipsel_24kc_musl/domoticz-db721738a19595d92f30eda8f56d0d4d250fd78a/hardware/OpenWebNetTCP.cpp: In member function 'void COpenWebNetTCP::UpdateDeviceValue(std::vector<bt_openwebnet>::iterator)':
/home/user/openwrt_2305/build_dir/target-mipsel_24kc_musl/domoticz-db721738a19595d92f30eda8f56d0d4d250fd78a/hardware/OpenWebNetTCP.cpp:1661:91: warning: format '%ld' expects argument of type 'long int', but argument 4 has type 'time_t' {aka 'long long int'} [-Wformat=]
 1661 |                                                 Log(LOG_STATUS, "Date/Time Change - now:%ld, rcv:%ld, delta: %d", now, rcv_tm, delta);
      |                                                                                         ~~^                       ~~~
      |                                                                                           |                       |
      |                                                                                           long int                time_t {aka long long int}
      |                                                                                         %lld
/home/user/openwrt_2305/build_dir/target-mipsel_24kc_musl/domoticz-db721738a19595d92f30eda8f56d0d4d250fd78a/hardware/OpenWebNetTCP.cpp:1661:100: warning: format '%ld' expects argument of type 'long int', but argument 5 has type 'time_t' {aka 'long long int'} [-Wformat=]
 1661 |                                                 Log(LOG_STATUS, "Date/Time Change - now:%ld, rcv:%ld, delta: %d", now, rcv_tm, delta);
      |                                                                                                  ~~^                   ~~~~~~
      |                                                                                                    |                   |
      |                                                                                                    long int            time_t {aka long long int}
      |                                                                                                  %lld
/home/user/openwrt_2305/build_dir/target-mipsel_24kc_musl/domoticz-db721738a19595d92f30eda8f56d0d4d250fd78a/hardware/OpenWebNetTCP.cpp:1675:90: warning: format '%ld' expects argument of type 'long int', but argument 4 has type 'time_t' {aka 'long long int'} [-Wformat=]
 1675 |                                                 Log(LOG_STATUS, "Date/Time is OK - now:%ld, rcv:%ld, delta: %d", now, rcv_tm, delta);
      |                                                                                        ~~^                       ~~~
      |                                                                                          |                       |
      |                                                                                          long int                time_t {aka long long int}
      |                                                                                        %lld
/home/user/openwrt_2305/build_dir/target-mipsel_24kc_musl/domoticz-db721738a19595d92f30eda8f56d0d4d250fd78a/hardware/OpenWebNetTCP.cpp:1675:99: warning: format '%ld' expects argument of type 'long int', but argument 5 has type 'time_t' {aka 'long long int'} [-Wformat=]
 1675 |                                                 Log(LOG_STATUS, "Date/Time is OK - now:%ld, rcv:%ld, delta: %d", now, rcv_tm, delta);
      |                                                                                                 ~~^                   ~~~~~~
      |                                                                                                   |                   |
      |                                                                                                   long int            time_t {aka long long int}
      |                                                                                                 %lld


[220/273] Building CXX object CMakeFiles/domoticz.dir/notifications/NotificationFCM.cpp.o
/home/user/openwrt_2305/build_dir/target-mipsel_24kc_musl/domoticz-db721738a19595d92f30eda8f56d0d4d250fd78a/notifications/NotificationFCM.cpp: In member function 'bool CNotificationFCM::getSlAccessToken(const std::string&, std::string&)':
/home/user/openwrt_2305/build_dir/target-mipsel_24kc_musl/domoticz-db721738a19595d92f30eda8f56d0d4d250fd78a/notifications/NotificationFCM.cpp:249:95: warning: format '%ld' expects argument of type 'long int', but argument 4 has type 'uint64_t' {aka 'long long unsigned int'} [-Wformat=]
  249 |                         _log.Debug(DEBUG_EVENTSYSTEM, "FCM: Using Cached Token! (Expires at %ld)", m_slAccessToken_exp_time);
      |                                                                                             ~~^    ~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                               |    |
      |                                                                                               |    uint64_t {aka long long unsigned int}
      |                                                                                               long int
      |                                                                                             %lld
/home/user/openwrt_2305/build_dir/target-mipsel_24kc_musl/domoticz-db721738a19595d92f30eda8f56d0d4d250fd78a/notifications/NotificationFCM.cpp:281:112: warning: format '%ld' expects argument of type 'long int', but argument 5 has type 'uint64_t' {aka 'long long unsigned int'} [-Wformat=]
  281 |                                 _log.Debug(DEBUG_EVENTSYSTEM, "FCM: AccessToken retrieved (%s...) expires in %ld seconds (at %ld)", slAccessToken.substr(0,10).c_str(), slAccessToken_exp_seconds, m_slAccessToken_exp_time);
      |                                                                                                              ~~^                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                |                                                        |
      |                                                                                                                long int                                                 uint64_t {aka long long unsigned int}
      |                                                                                                              %lld
/home/user/openwrt_2305/build_dir/target-mipsel_24kc_musl/domoticz-db721738a19595d92f30eda8f56d0d4d250fd78a/notifications/NotificationFCM.cpp:281:128: warning: format '%ld' expects argument of type 'long int', but argument 6 has type 'uint64_t' {aka 'long long unsigned int'} [-Wformat=]
  281 |                                 _log.Debug(DEBUG_EVENTSYSTEM, "FCM: AccessToken retrieved (%s...) expires in %ld seconds (at %ld)", slAccessToken.substr(0,10).c_str(), slAccessToken_exp_seconds, m_slAccessToken_exp_time);
      |                                                                                                                              ~~^                                                                   ~~~~~~~~~~~~~~~~~~~~~~~~
      |                                                                                                                                |                                                                   |
      |                                                                                                                                long int                                                            uint64_t {aka long long unsigned int}
      |                                                                                                                              %lld


```

### PR DESCRIPTION
**Pull request by kiddigital**
This PR addresses some small issues with the Google Firebase Cloud Messaging (FCM) notification subsystem.

Code refactored to make it more readable (create proper JSON object instead of raw binary data).

dzVents notify function does not pass a domoticz device id when possible (i.e. `on device` events).

When using the FCM subsystem (mobile app for example) and dzVents event is triggered by an `on device` event, you can now pass the `device.id` of the device to the notify function using the `extra` parameter.
```
return {
	on = {
		devices = {
			'DommyDev1'
		}
	},
	execute = function(domoticz, device)
		domoticz.notify("dzVentsSubjectDommeyDev1" , "dzVents message from DommyDev1" , domoticz.PRIORITY_HIGH,domoticz.NO_SOUND, device.id, "fcm" )
	end
}
```
This way the application (mobileapp for example) that receives the notification can now find out which Domoticz device triggered the notification (actually which device triggered the dzVents event script which called the `notify` :) ). This off course only works for notifications triggered by device events and not by timers, etc.

### CODE REVIEW

**Comment by kiddigital** [comment]
@Olifant1990 , can you check this PR as I noticed that you wrote some of the original GCM/FCM and dzVents notification pieces? thx

File: main/EventSystem.cpp [hunk 1]
```diff
@@ -3170,12 +3170,13 @@ bool CEventSystem::processLuaCommand(lua_State *lua_state, const std::string &fi
 		if (aParam.size() > 3) {
 			sound = aParam[3];
 		}
-		if (aParam.size() > 4) {
-			if (aParam[4].find("midx_") != std::string::npos) {
-				extraData = aParam[4];
+		if (aParam.size() > 4 && !aParam[4].empty()) {
+			if (isInt(aParam[4]) && aParam.size() > 5 && !aParam[5].empty() && aParam[5] == "fcm") {
```
Comment (Olifant1990) [inline main/EventSystem.cpp:3174]: I am personally not happy with this if/else, now you can't combine extraData parts.
For example if you want to send id FROM device 123 TO only mobile divice midx 456.
Then users can fill in midx_456|123?
Or 123|midx_456?
The pipe is only a seperator.

Also it is not sure if aParam[5] on this row, as the if says aParam.size() > 4

File: main/EventSystem.cpp [hunk 2]
```diff
@@ -3170,12 +3170,13 @@ bool CEventSystem::processLuaCommand(lua_State *lua_state, const std::string &fi
...
+					// Only FCM notification Subsystem handles extraData "|Device=<deviceIdx>"
+					extraData = "|Device=" + aParam[4];
```
Comment (Olifant1990) [inline main/EventSystem.cpp:3176]: So, as for previous comment, I think you should not start with a pipe...

File: notifications/NotificationFCM.cpp [hunk 3]
```diff
@@ -95,18 +95,33 @@ bool CNotificationFCM::SendMessageImplementation(
...
 
-		while (std::getline(tempssstr, temp, '|')) {
-			vExtraData.push_back(temp);
+				while (std::getline(tempssstr, temp, '|')) {
+					vExtraData.push_back(temp);
+				}
+			}
+		}
+		else {
+			sExtraData = ExtraData;
```
Comment (Olifant1990) [inline notifications/NotificationFCM.cpp:124]: sExtraData is only filled here?
Shouldn't we pass the full extraData to the phone on r170?
So the phone can handle the extraData itself?

File: notifications/NotificationFCM.cpp [hunk 4]
```diff
@@ -95,18 +95,33 @@ bool CNotificationFCM::SendMessageImplementation(
 {
 	//send message to FCM
 
-	std::string sMidx;
+	uint64_t AltIdx = Idx;
```
Comment (Olifant1990) [inline notifications/NotificationFCM.cpp:98]: No need to declare a new uint64, as Idx parameter is already a FROM device idx. All the logic is here already to handle the sending device, no need to get it from extraData here.
Maybe we need to change the call to the SendMessageImplementation, so de from device is removed from extraData and put in as first argument?

File: notifications/NotificationFCM.cpp [hunk 5]
```diff
@@ -95,18 +95,33 @@ bool CNotificationFCM::SendMessageImplementation(
...
-		std::string temp;
-		std::stringstream tempssstr { ExtraData };
+	if (!ExtraData.empty()) {
+		_log.Debug(DEBUG_EVENTSYSTEM, "FCM: ExtraData found! (%s) (deviceid %ld)", ExtraData.c_str(), static_cast<unsigned long>(Idx));
+		if (ExtraData.find("midx_") != std::string::npos) {
+			sMidx = ExtraData.substr(5);
+			stdreplace(sMidx, ";", ",");
+		}
+		else if (ExtraData.find("|") != std::string::npos) {
+			if (ExtraData.find("|Device=") == 0) {
```
Comment (Olifant1990) [inline notifications/NotificationFCM.cpp:108]: So all this parsing is not needed, see above comment

File: notifications/NotificationFCM.cpp [hunk 6]
```diff
@@ -139,19 +154,20 @@ bool CNotificationFCM::SendMessageImplementation(
 	}
 
 	// Add the default 'data' fields we always want to send if available
-	vExtraData.push_back("deviceid=" + std::to_string(Idx));
+	vExtraData.push_back("deviceid=" + std::to_string(AltIdx));
```
Comment (Olifant1990) [inline notifications/NotificationFCM.cpp:157]: Just use Idx, see previous comments

**Review by Olifant1990 — CHANGES_REQUESTED** [review]
Just a few thoughts, not breaking, but maybe worth a rethink?

File: main/EventSystem.cpp (hunk 1 above)
Comment (Olifant1990) [inline main/EventSystem.cpp:3174]: It is not sure if aParam[5] on this row

Comment (kiddigital) [reply main/EventSystem.cpp:3174]: Agreed. More refactoring could be useful.

Current 'issue' is that the `extraData` is used for multiple purposes in multiple notification subsystems.

midx for selecting certain receiving mobile devices is only available for FCM and currently only used AFAIK for the 'test' button in the DZ UI.

The specific '|Device=<somedzidx>' is used at more subsystems and now also by FCM.

Before, there was no way to pass a DZ deviceidx to the notification subsystems via the dzVents `notify()`. FCM now (ab)uses this existing method to get the 'missing' device Idx.

Rethinking the setup and goals might be needed and might need more rework 😁

File: main/EventSystem.cpp (hunk 2 above)
Comment (kiddigital) [reply main/EventSystem.cpp:3176]: It isn't as nice as it could be indeed.
Current 'problem' is that the presence of a pipe separator is the identifying characteristic that 1 or more key/value-pairs are available in the extraData. If there is only 1 key/value-pair (like in this case), there would be no separator and how than determine the difference between key/value-pair(s) and _normal_ extraData :) ?

File: notifications/NotificationFCM.cpp (hunk 4 above)
Comment (kiddigital) [reply notifications/NotificationFCM.cpp:98]: In most cases that is indeed correct.

Unfortunately, when a user uses the dzVents `notify()` function, no FROM device is passed (as there is no parameter in dzVents to pass this).
By _misusing_ the extraData parameter to pass a device Idx (see modification in Eventsystem.cpp), this omission in circumvented.
Hence we need an AltIdx (as the Idx is a `const` (which is ought to be anyway when done properly)).

Off course, a better solution would be to _fix_ the dzVents notify function. (@gizmocuz , any thoughts?)

File: notifications/NotificationFCM.cpp (hunk 3 above)
Comment (kiddigital) [reply notifications/NotificationFCM.cpp:124]: See above. 
We first have to determine if the extraData is _real_ extraData that should be handled by the receiver (mobileApp for example) or that it is 'creative' use of extraData like passing TO device using `midx_`, passing the FROM device using `|Device=`, or passing _key/value-pair(s)_ to add to the message structure. In these cases the value of extraData should __not__ be passed :)

**Comment by kiddigital** [comment]
@gizmocuz , I think @Olifant1990 is making good points with his comments.

The _challenge_ to tackle these points is that further refactoring is probably required and affects more notification subsystems than just FCM.

Suggestion could be to merge this PR as it is now as it addresses already existing _issues_ with the current code and gives the _dzVents_ users additional functionality (passing the FROM device Idx) that could be leveraged by the mobile App (like Android App issue [# 708](https://github.com/domoticz/domoticz-android/issues/708)).

Further refactoring/optimizing can be done in future PR's once we found a better approach to handle the current _creative use_ of the `extraData` field.

Maybe discuss this further on Slack/Forum?

**Comment by gizmocuz** [comment]
Of course we can discuss this on Slack
But the idea is to send simple push notifications to mobiles/apps
Of course there will be some users that would like to do more with it, but that's not 100% in scope here
But discussion is always a good idea

**Comment by rezzalex** [comment]
Happy to be part of the discussion on slack
